# 在玩家执行 /cpt join 后为玩家分配的默认竞赛的名称
# 留空则随机选择
default-campaign-name: ~
# 如果为 true，玩家只能在一个比赛中留下数据
# 当切换到另外的比赛时，先前比赛的数据会被删除
# 建议当此项为 true 时给玩家适当的提醒。
single-choice: false
# 如果为 true，自动在玩家登录的时候执行 /cpt join
# 如果执行不成功（例如所有的比赛都处于关闭状态），会为玩家发送一条提示
# 如果不需要这条提示，请启用 disable-auto-join-failure-warning。
auto-join-on-login: false
# 见上
disable-auto-join-failure-warning: false
# 当玩家在比赛中途退出服务器后，要将其进度保存多久
# 单位：秒，整数
# 如果设置为 0，则不为中途退出服务器的玩家保存任何数据
# 如果为正数，当中途退出服务器的玩家迟于该期限上线，不能继续进度
# 如果为负数，表示不设期限（不建议）
halfway-progress-deadline: 0
# 允许在一段之间停留的最长时间
# 单位：秒，整数
# 在单段停留超出此时间，整场比赛的数据会被重置，并提示玩家
timer-max-timeout: 120
# 是否在玩家下线后仍然计时
allow-timer-working-offline: false
# 是否允许玩家手动使用 /cpt resume 继续比赛
allow-resume: true
# 如果为 true，会在玩家上线的时候自动尝试继续其比赛
# 如果执行不成功（例如期限已过），会为玩家发送一条提示
# 如果不需要这条提示，请启用 disable-auto-resume-failure-warning。
auto-resume-on-login: false
disable-auto-resume-failure-warning: false
# 将所有选取的检测范围扩大指定的格数（x y z 三个方向）
point-detection-offset: 0