name: CheckPoint
version: '${version}'
main: red.oases.checkpoint.CheckPoint
api-version: '1.20'
commands:
  checkpoint:
    aliases: ['cpt']
    description: Checkpoint main command.
    permission: checkpoint.user
permissions:
  checkpoint.admin:
    default: op
    description: 完全访问 Checkpoint 的权限
  checkpoint.user:
    default: true
    description: 玩家权限